import { Event } from "@/components/table/columns"

export const events: Event[] = [
    {
        id: "1",
        activity: "Attività 1",
        organizerSection: "Brennero",
        targetGroup: "728ed52f",
        activityType: "biking",
        startDate: new Date("2024/02/01"),
        durationDays: 1,
        endDate: new Date("2024/02/15"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 1,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "2",
        activity: "Attività 2",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "biking",
        startDate: new Date("2024/04/01"),
        durationDays: 1,
        endDate: new Date("2024/04/15"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 1,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "3",
        activity: "Attività 3",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "biking",
        startDate: new Date("2024/02/15"),
        durationDays: 1,
        endDate: new Date("2024/02/20"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 1,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "4",
        activity: "Attività 4",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "728ed52f",
        startDate: new Date("2024/03/15"),
        durationDays: 1,
        endDate: new Date("2024/03/19"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 1,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "5",
        activity: "Attività 5",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "728ed52f",
        startDate: new Date("2024/12/02"),
        durationDays: 1,
        endDate: new Date("2024/12/04"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 783,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "6",
        activity: "Attività 6",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "728ed52f",
        startDate: new Date("2025/02/15"),
        durationDays: 1,
        endDate: new Date("2025/02/17"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 600,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "7",
        activity: "Attività 7",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "728ed52f",
        startDate: new Date("2024/02/15"),
        durationDays: 1,
        endDate: new Date("2024/02/15"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 1,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "8",
        activity: "Attività 8",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "728ed52f",
        startDate: new Date("2024/02/15"),
        durationDays: 1,
        endDate: new Date("2024/02/15"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 882,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "9",
        activity: "Attività 9",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "728ed52f",
        startDate: new Date("2024/02/15"),
        durationDays: 1,
        endDate: new Date("2024/02/15"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 1,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "10",
        activity: "Attività 10",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "728ed52f",
        startDate: new Date("2024/02/15"),
        durationDays: 1,
        endDate: new Date("2024/02/15"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 2000,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
    {
        id: "11",
        activity: "Attività 1",
        organizerSection: "728ed52f",
        targetGroup: "728ed52f",
        activityType: "728ed52f",
        startDate: new Date("2024/02/15"),
        durationDays: 1,
        endDate: new Date("2024/02/15"),
        estimatedHours: 1,
        difficulty: "728ed52f",
        elevationGain: 197,
        elevationLoss: 2,
        location: "728ed52f",
        flyerLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        gpxTrackLink: "https://www.cai.it/gruppo_regionale/gp-alto-adige/",
        contactPhone: "728ed52f",
        contactEmail: "728ed52f",
    },
  ];